### ISSUE TITLE
[Format] Allow overriding the docker container used for swift-format

### ISSUE THREAD

**Issue by fabianfett** [swiftlang/github-workflows#20]
https://github.com/swiftlang/github-workflows/blob/66ec6fb4b94e9a5fe4da5b4b8982c7479640f277/.github/workflows/soundness.yml#L150

We should allow users to override the docker container that is used for running the format soundness check. 

### Reason

Swift 6.0 does not understand the `sending` keyword. https://github.com/swiftlang/swift-syntax/issues/2836 We would like to force the 6.0 nightly in our project.

See open PR that can't use the workflows defined here:
https://github.com/swift-server/swift-aws-lambda-runtime/pull/405

**Comment by FranzBusch** [comment]
Done in https://github.com/swiftlang/github-workflows/pull/21
