### ISSUE TITLE
Add optional SwiftFormat configuration file

### ISSUE THREAD

**Issue by GErP83** [swiftlang/github-workflows#33]
Some teams may prefer to use their own configuration when running SwiftFormat.

This can be supported using the "--configuration" parameter. The script can then also check for an optional .swiftformat file at the root of the repository.

Is this feature being considered? I’d be happy to implement it

**Comment by FranzBusch** [comment]
This repository uses https://github.com/swiftlang/swift-format for the formatting workflow. Placing a `.swift-format` file at the root of the repo should get picked up automatically.

**Comment by GErP83** [comment]
Thank you for the answer!
